### ISSUE TITLE
[BUG] Bot wont start, Getting an unknown error. 

### ISSUE THREAD

**Issue by Motzumoto** [Aaronidk/Dorito-bot-discord.js#10]
I click the install.bat, it gets done installing then i try to click Start Bot.bat but it wont start, ive put the bot token and my discord id into the config already, i dont know what im missing. 

here is the error i get. 
![image](https://user-images.githubusercontent.com/45925152/75116411-16440280-5636-11ea-85d3-1a393854a5f4.png)

Just tell me what to install/what to do, that would be appreciated.

**Comment by Uthsho** [comment]
You put a invalid token

**Comment by Computer-Man497** [comment]
Make sure you added a token to the config file, make sure it's correct as well.
