### ISSUE TITLE
Testers needed

### ISSUE THREAD

**Issue by Aaronidk** [Aaronidk/Dorito-bot-discord.js#14]
Hi, Since i've updated the code I need testers to test if everything works fine. Thanks.

**Comment by Uthsho** [comment]
I could help

**Comment by Aaronidk** [comment]
Thank you :) Can you test if all the commands work fine and there are no bugs. Also if there are any improvments I can make please tell me. :D

**Comment by Uthsho** [comment]
Invite me to ur test server?

**Comment by Uthsho** [comment]
Add me MrSon#0255
