### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Uthsho** [Aaronidk/Dorito-bot-discord.js#16]
Hi there. I have a question. I can provide you a good quality music system but it is not complete yet 
but you can check it and see if you like it. Please add me in discord: MrSon#0255

**Comment by Uthsho** [comment]
Hi there ! You here? i change my discord username: GalaxySon#0255

**Comment by Uthsho** [comment]
Hey There! I have changed my name again so now its permanently: MrSon#0255.

Could I like help you add more cool features to the bot?

**Comment by Aaronidk** [comment]
sorry for a late response. I’m interested, if you can message me on discord @Aaron#7444 that would be great

**Comment by Uthsho** [comment]
Alright!

**Comment by Uthsho** [comment]
I have sent you request my name is MrSon#0255 (:

**Comment by Uthsho** [comment]
Ya so I changed my name, so my name is 𝐍𝐋™乛MrSon#0255 lol
