### ISSUE TITLE
Remove the 24/7 Guide in ReadMe.md

### ISSUE THREAD

**Issue by DeltaCoderr** [Aaronidk/Dorito-bot-discord.js#18]
**Describe the bug**
Well, I checked your Readme.md and Well in the idiots guide link it is clearly said "**It is strongly advised you actually shell out a couple dollars a month and get an actual real VPS, due to the free nature of Glitch it has led to a high number of Glitch based IP's getting API banned by Discord due to abuse and now Glitch are actively banning users for using external site pingers such as Uptimerobot.**"

**To Reproduce**
Well, I suggest removing it or I can just make a PR if it's okay with you?

**Comment by Aaronidk** [comment]
sure that’s okay

**Comment by Aaronidk** [comment]
Thanks for the edits

**Comment by Aaronidk** [comment]
thanks for the edits

**Comment by Aaronidk** [comment]
.

**Comment by DeltaCoderr** [comment]
np
