### ISSUE TITLE
Music is being redone

### ISSUE THREAD

**Issue by Aaronidk** [Aaronidk/Dorito-bot-discord.js#22]
Since the previous music commands were garbage, i'm just going to make new ones. The next bot release will contain music.

**Comment by DeltaCoderr** [comment]
Looking forward to this one 👍

**Comment by Uthsho** [comment]
Hello there! Could I help in making the music stuff?

**Comment by Uthsho** [comment]
hey Aaron i sent u friend request as u gave me ur username in a issue. Please accept my friend request and i can help u make a powerful music feature!
