### ISSUE TITLE
Testers Needed 

### ISSUE THREAD

**Issue by Aaronidk** [Aaronidk/Dorito-bot-discord.js#24]
The bot has finally been updated and a lot of issues have been fixed.
To make sure everything is running smoothly I need some testers to see if commands work fine and to see how the bot runs on different computers.

**Comment by JUPITEER09** [comment]
can you give us the bot invite url ?

**Comment by tovade** [comment]
can you give us the server invite link

**Comment by JUPITEER09** [comment]
bruh

**Comment by Aaronidk** [comment]
The bot invite link is in the readme. Please report bugs and issues on the issues page of this repository

**Comment by EMPERRORPK007** [comment]
I will help
