### ISSUE TITLE
Bot running twice

### ISSUE THREAD

**Issue by galaxine-senpai** [Aaronidk/Dorito-bot-discord.js#34]
so it runs it twice can this be fixed

**Comment by Atul1409** [comment]
bots sometimes run twice if it is running on two instances a simple solution is changing the bot token or restart

https://support.glitch.com/t/discord-bot-scripts-running-twice-2-bots-at-once/27177

**Comment by galaxine-senpai** [comment]
ive done this many times no difference

**Comment by Atul1409** [comment]
Have you tried changing bot token ?

**Comment by Aaronidk** [comment]
This is not an issue with the bot so I am closing this issue
