### ISSUE TITLE
Sends a command twice

### ISSUE THREAD

**Issue by louis842** [Aaronidk/Dorito-bot-discord.js#39]
it says

**_Bot User Anero has been logged in and is ready to use!_**

twice and it sends the same message 2 times help would be appreciated

**Comment by louis842** [comment]
![image](https://user-images.githubusercontent.com/63163022/106971474-ef97b280-6746-11eb-951a-0b50f7b0dda4.png)

**Comment by Aaronidk** [comment]
are you using cmd to run the bot
