### ISSUE TITLE
Bot can't read the token

### ISSUE THREAD

**Issue by xyz-Yanys** [Aaronidk/Dorito-bot-discord.js#41]
I followed the tutorial, but at the end, it gives me this error:
`Logging into Bot User...
(node:13920) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.`
what should I do to handle it?

**Comment by Aaronidk** [comment]
Make sure your token is correct and also make sure its pasted in between quotes ""
