### ISSUE TITLE
Music command, It connects but nothing plays.

### ISSUE THREAD

**Issue by Mairoooon** [Aaronidk/Dorito-bot-discord.js#8]
When you put a song and connect to a voice channel, the bot does not play anything.

The bot already has the YouTube API and its token and other configurations made.

I hope you answer as soon as possible, thanks.

**Comment by Uthsho** [comment]
lol the music module the music uses doesn't work

**Comment by Aaronidk** [comment]
As Uthsho said the music module is no longer being updated or maintained. I am either going to find an alternative or just remove the music module completely.
